### ISSUE TITLE
Snippet of code is being executed

### ISSUE THREAD

**Issue by henriquecf** [Polymer/marked-element#12]
Hello. As I was doing a demo for a presentation, getting issues from github and taking their body and using the marked-element to print the markdown.

Unexpectedly, it executed the code and changed my app in Chrome (altough in Firefox it did not).

The example I used is actually from a polymer issue from the github api, so this code should show the error:

``` html
<html>
  <head>
    <base href="http://polygit.org/polymer+:master/components/">
    <link href="polymer/polymer.html" rel="import">
    <link href="marked-element/marked-element.html" rel="import">
    <link href="iron-ajax/iron-ajax.html" rel="import">
  </head>

  <body unresolved>
    <template is="dom-bind" id="app">
      <iron-ajax url="https://api.github.com/repos/Polymer/polymer/issues/2481" last-response="{{issue}}" auto></iron-ajax>
      <marked-element markdown="{{issue.body}}">
        <div class="markdown-html"></div>
      </marked-element>
    </template>
  </body>
</html>
```

**Comment by ebidel** [comment]
This is actually for the 1.0 element, but the `markdown` attribute sets the `innerHTML` of the element. That means that any markup will be rendered. This is WAI.

https://github.com/PolymerElements/marked-element/blob/master/marked-element.html#L158
