### ISSUE TITLE
When text attribute is set to blank innerHTML is not set to blank

### ISSUE THREAD

**Issue by chuckh** [Polymer/marked-element#5]
Need to add below else to textChanged. Otherwise previous value of innerHTML is displayed.
```
textChanged: function (oldVal, newVal) {
      if (newVal) {
        this.innerHTML = marked(this.text);
      } else {
        this.innerHTML = "";
      }
    },
```

**Comment by ssorallen** [comment]
@chuckh, can you add a test case for this? That would be good to close this issue since your feature addition was merged.

**Comment by chuckh** [comment]
@ssorallen I created simple example at http://jsbin.com/wuyogi/2/edit?html,output with a Click to Clear Text button at the bottom. 

I ran into this problem using firebase, binding and the marked-element. I don't have simple example for it.
